"""
Data models for the Docusaurus ingestion pipeline.
Defines the core entities: Content Chunk, Embedding Vector, and Metadata.
"""
from dataclasses import dataclass
from typing import List, Optional
from datetime import datetime


@dataclass
class ContentChunk:
    """
    Represents a segment of text extracted from Docusaurus pages.
    
    Fields:
    - id (string): Unique identifier for the chunk
    - url (string): Source URL of the content
    - section (string): Section identifier from the Docusaurus site
    - content (string): The actual text content of the chunk
    - chunk_index (integer): Position of this chunk within the source document
    - created_at (datetime): Timestamp when the chunk was created
    """
    id: str
    url: str
    section: str
    content: str
    chunk_index: int
    created_at: datetime = datetime.now()
    
    def __post_init__(self):
        """Validate the content chunk after initialization."""
        if not self.url or not self.url.strip():
            raise ValueError("URL must be a valid, non-empty string")
        
        # Note: We're not validating content length against Cohere's limits here
        # as this would require knowledge of the specific model being used
        # This validation will happen at the embedding stage


@dataclass
class EmbeddingVector:
    """
    High-dimensional vector representation of text content generated by Cohere models.
    
    Fields:
    - id (string): Unique identifier that matches the Content Chunk ID
    - vector (array of floats): The embedding vector values
    - model_name (string): Name of the Cohere model used to generate the embedding
    - created_at (datetime): Timestamp when the embedding was generated
    """
    id: str
    vector: List[float]
    model_name: str
    created_at: datetime = datetime.now()
    
    def __post_init__(self):
        """Validate the embedding vector after initialization."""
        if not self.vector:
            raise ValueError("Vector must be a non-empty list of floats")
        
        if not self.model_name or not self.model_name.strip():
            raise ValueError("Model name must be a valid, non-empty string")


@dataclass
class Metadata:
    """
    Structured information about each content chunk stored with embeddings in Qdrant.
    
    Fields:
    - url (string): Source URL of the content
    - section (string): Section identifier from the Docusaurus site
    - chunk_id (string): ID of the content chunk
    - source_title (string): Title of the source page (optional)
    - processed_at (datetime): Timestamp when the content was processed
    """
    url: str
    section: str
    chunk_id: str
    source_title: Optional[str] = None
    processed_at: datetime = datetime.now()
    
    def __post_init__(self):
        """Validate the metadata after initialization."""
        if not self.url or not self.url.strip():
            raise ValueError("URL must be a valid, non-empty string")
        
        if not self.chunk_id or not self.chunk_id.strip():
            raise ValueError("Chunk ID must be a valid, non-empty string")